### PR TITLE
Adding ML Model passes

### PR DESCRIPTION
**Pull request by bhushan23**

### CODE REVIEW

**Comment by aseemw** [comment]
can we add a unit test? Where there was a hanging layer, which gets removed after this PR?

**Comment by 1duo** [comment]
Similar test cases like this: https://github.com/apple/coremltools/blob/master/coremltools/converters/tensorflow/test/test_graph_passes.py

**Comment by bhushan23** [comment]
> Similar test cases like this: https://github.com/apple/coremltools/blob/master/coremltools/converters/tensorflow/test/test_graph_passes.py

test case added

**Comment by 1duo** [comment]
> > Similar test cases like this: https://github.com/apple/coremltools/blob/master/coremltools/converters/tensorflow/test/test_graph_passes.py
> 
> test case added

Just curious, is this test also running in CI?

**Comment by bhushan23** [comment]
> > > Similar test cases like this: https://github.com/apple/coremltools/blob/master/coremltools/converters/tensorflow/test/test_graph_passes.py
> > 
> > 
> > test case added
> 
> Just curious, is this test also running in CI?

yes

**Pull request merged**
