### PR TITLE
Add model zoo tests to Travis CI

### PR DESCRIPTION
**Pull request by aseemw**
I think it is more convenient to separate the testing of backend tests into node and model tests. Hence in this PR I have made two separate files: tests/onnx_backend_models_test.py and tests/onnx_backend_node_test.py. 

We first want to make sure all the 9 model zoo tests pass.  Of the 9 test,  "test_densenet121" is failing due to a small numerical mismatch (only slightly more than .001). @smessmer Is there a way to modify the tolerance for a specific test?

### CODE REVIEW

**Comment by smessmer** [comment]
The CI error is due to test dependencies from setup.py not being installed. Seems they're only automatically installed if you use `python setup.py test`. You should still be able to select an individual test module to run by calling `python setup.py test -m your.package.tests.test_module`.

**Comment by aseemw** [comment]
I see, so the following changes should work then?

time python setup.py test -m tests/transformers_test.py
time python setup.py test -m tests/convert_test.py
etc

**Comment by smessmer** [comment]
At least it should fix the current issue ;)
Btw, I think it has to be a module name, so no .py extension

**Comment by aseemw** [comment]
It seems the -m flag is incorrect

**Comment by smessmer** [comment]
Hm still doesn't seem to work, sorry about this. I've got the info from https://stackoverflow.com/questions/21167516/does-unittest-allow-single-case-suite-testing-through-setup-py-test . They also propose a '-s' parameter instead of '-m'. Does that one work? Btw any solution not working locally won't work on Travis either. There shouldn't be many differences in thr setup.

**Comment by smessmer** [comment]
In the worst case, we could do "python setup.py test", which will fail but should install test dependencies before failing. Then afterwards, we could run the test files directly as you had it initially.

To call setup.py and allow it failing without failing the CI run, you could call

    python setup.py test || true

**Comment by aseemw** [comment]
Sure, it should work locally. -s flag doesn't seem to work either. I'll try to see if there is any other solution, otherwise I'll go with your suggestion of running setup.py and letting it fail.

**Comment by smessmer** [comment]
If '-m' works locally but not on CI, is there maybe a different version of setuptools installed? We could probably add a command to update the CI setuptools version.


-------- Original message --------

**Comment by aseemw** [comment]
Actually -m does not work locally either

**Comment by smessmer** [comment]
I just experimented a bit locally and got this working:

    python setup.py test --addopts tests/transformers_test.py

**Comment by aseemw** [comment]
Awesome, yeah that works locally for me too. I'll update the PR with that one.

**Comment by bddppq** [comment]
Using a test driver (e.g. pytest, nosetests) is in general good in python projects, you will get many features via their plugins (e.g. pytest has nbval for testing jupyter notebooks, xdist for running tests in parallel, pytest-cov for line-based coverage stats). Besides, onnx backend test converage report is implemented as a pytest plugin, so I would suggest to use pytest in onnx-coreml as well.

**Comment by smessmer** [comment]
I agree on the test drivers. The issue is though that the test driver (i.e. pytest) and its dependencies are listed in setup.py and not installed by calling `python setup.py install`, so pytest isn't present. We could just manually call `pip install pytest` in CI before calling pytest, but this seems like a bad idea because test dependencies might change and they are already listed in setup.py, no reason to list them again in the CI setup. Afaik, there is no way to install test dependencies from setup.py, but they will be automatically installed when you call `python setup.py test`.

That's why I think we should use `python setup.py test` to call the test cases. This, however, doesn't contradict using something like `pytest` as test runner. I think `python setup.py test` can call into these test runners.

However, I propose doing this separately. This PR already adds a lot of value by enabling a first set of test cases on CI and should land to increase our confidence in the CI runs.

**Comment by bddppq** [comment]
Sure it can be done in a separate PR.

There are couple ways I have seen people putting test dependencies.
1. Setting `tests_require` in setup.py, and `python setup.py test` will install them. Note this keyword is only recognized by setuptools, pip doesn't do anything with it.

2. Using a `tests-requirements.txt` file. So in both CI and locally, you do pip install -r `tests-requirements.txt` before running tests.

3. Using `extras_require`:
```
'extras_require': {
    'testing': ['pytest'],
}
```
```
pip install .[testing]
```

**Comment by smessmer** [comment]
note: the Travis failure on Linux python2 is unrelated. I'm already working on it. We can ignore that one in the context of this PR

**Pull request merged**
