### PR TITLE
Fix failing tests in operators_test.py

### PR DESCRIPTION
**Pull request by aseemw**
In the master 2 out of 19 tests are failing.

- a minor correction fixes "test_concat"

- "test_transpose_default" complains about undefined attribute 'perm', however, by default it should reverse the input. Is it a version issue?

### CODE REVIEW

**Comment by aseemw** [comment]
@dzhulgakov The following test fails:

`pytest tests/operators_test.py::SingleOperatorTest::test_transpose_default` with the error:

> onnx-coreml/third_party/onnx/onnx/common/ir.h:252: find: Assertion `!required || it != values_.end()` failed: /Users/aseem/Documents/code/FB/onnx-coreml-aseem/onnx-coreml/third_party/onnx/onnx/common/ir.h:252: find: required undefined attribute 'perm'

According to the docs, "perm" attribute is not required for the "transpose" node. Just conforming, if the attribute is really required, I'll just update the test accordingly.

**Comment by bddppq** [comment]
@aseemw You are right it's indeed not a required attribute. The error should come from the optimization passes that fuse/eliminate the Transpose operators. 
@anderspapitto Could you take a took?

**Comment by houseroad** [comment]
@bddppq @anderspapitto I just checked. Indeed, it is a bug. I will fix it soon.

Thanks for reporting this. @aseemw

**Comment by dzhulgakov** [comment]
Lu already sent the fix in https://github.com/onnx/onnx/pull/559 for the perm issue - thanks!

As for these tests - would be nice to merge them to the main onnx tests at some point (see https://github.com/onnx/onnx/blob/master/docs/OnnxBackendTest.md)

**Comment by smessmer** [comment]
@dzhulgakov There should be an item for moving them to onnx in https://github.com/onnx/onnx-coreml/issues/35

**Pull request merged**
