### PR TITLE
Add mypy type checker

### PR DESCRIPTION
**Pull request by smessmer**
This allows calling
$ mypy .
to run static type checks.

Currently, very lenient settings are used, but they should be made more strict once the code conforms to the stricter rules.

### CODE REVIEW

**Comment by bddppq** [comment]
Hmm directly invoking `mypy` should be less typing than `python setup.py mypy` :-)

Also mypy should not be an `install_requires` of onnx-coreml, it's just a dev dependency, in setup.py the closest approximate to this is `extras_require`.

**Comment by smessmer** [comment]
The `python setup.py mypy` thing is for setting the arguments to the `mypy` call, i.e. which checks are enabled and which not.

I'll move the dependency to `extras_require`.

**Comment by bddppq** [comment]
This is the right way to do configs: http://mypy.readthedocs.io/en/latest/config_file.html

**Comment by smessmer** [comment]
@bddppq Incorporated your comments. Users have to call "mypy .", not just "mypy", but that's probably good enough. If you know a way of also specifying the directory to run on in setup.cfg, let me know.

Please ignore the failing CI, it's not set up correctly yet.

**Pull request merged**
