### PR TITLE
Add a unit test: fc + convnet

### PR DESCRIPTION
**Pull request by aseemw**

### CODE REVIEW

**Comment by jbmaxwell** [comment]
Sorry, I'm not able to get this to run properly... I'm pretty new to python... 
I fetched the pull request, then cd-ed into `onnx-coreml/tests/`. But just trying `python model_test.py` doesn't seem to work—all 13 tests fail.

**Comment by aseemw** [comment]
please see https://github.com/onnx/onnx-coreml#running-unit-tests
you will need Mac to run the test, since coremltools calls predict using the underlying CoreML framework

**Comment by jbmaxwell** [comment]
Yeah, I've noticed that... I have a Mac, but my dev environments are all on an Ubuntu box... I could install the basics to run it. But is the point that you have no issues running that conversion? If so, then I'll look further into what might be wrong, either in my environment, or just my conversion code.

**Comment by jbmaxwell** [comment]
Actually, it does seem to convert the model:

```1/18: Converting Node Type Gemm
2/18: Converting Node Type Relu
3/18: Converting Node Type Gemm
4/18: Converting Node Type Reshape
5/18: Converting Node Type ConvTranspose
6/18: Converting Node Type BatchNormalization
7/18: Converting Node Type Relu
8/18: Converting Node Type ConvTranspose
9/18: Converting Node Type BatchNormalization
10/18: Converting Node Type Relu
11/18: Converting Node Type ConvTranspose
12/18: Converting Node Type BatchNormalization
13/18: Converting Node Type Relu
14/18: Converting Node Type ConvTranspose
15/18: Converting Node Type BatchNormalization
16/18: Converting Node Type Relu
17/18: Converting Node Type ConvTranspose
18/18: Converting Node Type Sigmoid
Translation to CoreML spec completed. Now compiling the CoreML model.
Model Compilation done.
```

**Pull request merged**
