### PR TITLE
Add Gather operation

### PR DESCRIPTION
**Pull request by pokidyshev**

### CODE REVIEW

**Comment by aseemw** [comment]
gather operation has been added in version 4 of the spec. 
Apart from adding the translation function, need to also upgrade the version number of CoreML spec,  and need to modify the "shape_mapping". With version 4, the onnx shapes no longer need to be mapped to CoreML shapes of Seq,B,C,H,W. They can be free rank and same as onnx. 
This is a change across the converter, which we will be making in near future. 

For this PR, to use the new layers, flag ``disable_rank5_shape_mapping`` needs to be used with the builder, as in here: https://github.com/apple/coremltools/blob/master/coremltools/test/test_numpy_nn_layers.py#L3229

Also, it would be great to add a test.

**Comment by bhushan23** [comment]
@pokidyshev any update?

**Comment by julien-c** [comment]
An ETA on this would be awesome. Thank you

**Comment by bhushan23** [comment]
@pokidyshev We have added support for Gather op in CoreML 3
Thank you for your contribution !!

Closing current PR.

**Pull request closed without merging**
